export const contractAddress = "0xa49A70ac6bD9B8a8059Fdf154529F3e8A03051c5";
export const abi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "addBuyOrder",
    inputs: [
      { name: "_amount", type: "uint256", internalType: "uint256" },
      { name: "_price", type: "uint256", internalType: "uint256" },
      { name: "_fiat", type: "uint8", internalType: "enum P2P1.Fiat" },
      { name: "_accountNumber", type: "uint256", internalType: "uint256" },
      { name: "_bank", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addSellOrder",
    inputs: [
      { name: "_amount", type: "uint256", internalType: "uint256" },
      { name: "_price", type: "uint256", internalType: "uint256" },
      { name: "_fiat", type: "uint8", internalType: "enum P2P1.Fiat" },
      { name: "_accountNumber", type: "uint256", internalType: "uint256" },
      { name: "_bank", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "spender", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buyOrder",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "price", type: "uint256", internalType: "uint256" },
      { name: "accountNumber", type: "uint256", internalType: "uint256" },
      { name: "bank", type: "string", internalType: "string" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "isComplete", type: "bool", internalType: "bool" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "buyer", type: "address", internalType: "address" },
      { name: "fiatCurrency", type: "uint8", internalType: "enum P2P1.Fiat" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "buyOrders",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "price", type: "uint256", internalType: "uint256" },
      { name: "accountNumber", type: "uint256", internalType: "uint256" },
      { name: "bank", type: "string", internalType: "string" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "isComplete", type: "bool", internalType: "bool" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "buyer", type: "address", internalType: "address" },
      { name: "fiatCurrency", type: "uint8", internalType: "enum P2P1.Fiat" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelBuyOrder",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelOrder",
    inputs: [
      { name: "_id", type: "uint256", internalType: "uint256" },
      { name: "isSellOrder", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelSellOrder",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "downliners",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllBuyOrders",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllCompleteBuyOrders",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllCompleteSellOrders",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllSellOrders",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBuyOrdersByFiat",
    inputs: [{ name: "_fiat", type: "uint8", internalType: "enum P2P1.Fiat" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getDownliners",
    inputs: [{ name: "upliner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOpenBuyOrders",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOpenSellOrders",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrdersByFiat",
    inputs: [
      { name: "_fiat", type: "uint8", internalType: "enum P2P1.Fiat" },
      { name: "isSellOrder", type: "bool", internalType: "bool" },
    ],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getSellOrdersByFiat",
    inputs: [{ name: "_fiat", type: "uint8", internalType: "enum P2P1.Fiat" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "myOpenBuyOrders",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "myOpenSellorders",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct P2P1.Order[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "price", type: "uint256", internalType: "uint256" },
          { name: "accountNumber", type: "uint256", internalType: "uint256" },
          { name: "bank", type: "string", internalType: "string" },
          { name: "messages", type: "string[]", internalType: "string[]" },
          { name: "isActive", type: "bool", internalType: "bool" },
          { name: "isComplete", type: "bool", internalType: "bool" },
          { name: "seller", type: "address", internalType: "address" },
          { name: "buyer", type: "address", internalType: "address" },
          {
            name: "fiatCurrency",
            type: "uint8",
            internalType: "enum P2P1.Fiat",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "releaseAsset",
    inputs: [
      { name: "_id", type: "uint256", internalType: "uint256" },
      { name: "isSellOrder", type: "bool", internalType: "bool" },
    ],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "schemaId",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sellOrder",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "price", type: "uint256", internalType: "uint256" },
      { name: "accountNumber", type: "uint256", internalType: "uint256" },
      { name: "bank", type: "string", internalType: "string" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "isComplete", type: "bool", internalType: "bool" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "buyer", type: "address", internalType: "address" },
      { name: "fiatCurrency", type: "uint8", internalType: "enum P2P1.Fiat" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sellOrders",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "price", type: "uint256", internalType: "uint256" },
      { name: "accountNumber", type: "uint256", internalType: "uint256" },
      { name: "bank", type: "string", internalType: "string" },
      { name: "isActive", type: "bool", internalType: "bool" },
      { name: "isComplete", type: "bool", internalType: "bool" },
      { name: "seller", type: "address", internalType: "address" },
      { name: "buyer", type: "address", internalType: "address" },
      { name: "fiatCurrency", type: "uint8", internalType: "enum P2P1.Fiat" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setSPInstance",
    inputs: [{ name: "instance", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setSchemaID",
    inputs: [{ name: "schemaId_", type: "uint64", internalType: "uint64" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setUpliner",
    inputs: [{ name: "upliner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "spInstance",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "contract ISP" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "tokenIncentive",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateBuyOrderToActive",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateBuyOrderToPaid",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateOrderToActive",
    inputs: [
      { name: "_id", type: "uint256", internalType: "uint256" },
      { name: "isSellOrder", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateOrderToPaid",
    inputs: [
      { name: "_id", type: "uint256", internalType: "uint256" },
      { name: "isSellOrder", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateSellOrderToActive",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateSellOrderToPaid",
    inputs: [{ name: "_id", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "upliners",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "spender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AssetReleased",
    inputs: [
      {
        name: "seller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "buyer",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "attestationId",
        type: "uint64",
        indexed: false,
        internalType: "uint64",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderCancelled",
    inputs: [
      { name: "id", type: "uint256", indexed: false, internalType: "uint256" },
      {
        name: "isSellOrder",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderCompleted",
    inputs: [
      { name: "id", type: "uint256", indexed: false, internalType: "uint256" },
      {
        name: "isSellOrder",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OrderCreated",
    inputs: [
      { name: "id", type: "uint256", indexed: false, internalType: "uint256" },
      {
        name: "isSellOrder",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RewardDistributed",
    inputs: [
      {
        name: "upliner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "depositor",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UplinerSet",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "upliner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "ERC20InsufficientAllowance",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "allowance", type: "uint256", internalType: "uint256" },
      { name: "needed", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ERC20InsufficientBalance",
    inputs: [
      { name: "sender", type: "address", internalType: "address" },
      { name: "balance", type: "uint256", internalType: "uint256" },
      { name: "needed", type: "uint256", internalType: "uint256" },
    ],
  },
  {
    type: "error",
    name: "ERC20InvalidApprover",
    inputs: [{ name: "approver", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC20InvalidReceiver",
    inputs: [{ name: "receiver", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC20InvalidSender",
    inputs: [{ name: "sender", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ERC20InvalidSpender",
    inputs: [{ name: "spender", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  { type: "error", name: "TradeConfirmationFailed", inputs: [] },
];
